import fs from 'fs'
import path from 'path'
import { importJs } from './js-import.mjs'
import { STAT_RULES, DEFAULT_STATS } from '../../js/core/constants.js'

/**
 * Runs the REAL runtime formulas (js/character.js computeStats, js/threat-level.js
 * computeThreatLevel, js/skill-level.js computeSkillLevel, js/combat-power.js
 * computeCombatPower) inside Node so the generator can solve for stats that
 * produce an exact target Threat Level — with zero risk of the build script's
 * math drifting from what the app actually shows a GM. Mocks `fetch` to serve
 * the already-built data/json/*.json files, then loads game data + cache once.
 */
let runtimeModules = null

function loadJsonSafe(filePath, fallback) {
  try {
    return JSON.parse(fs.readFileSync(filePath, 'utf8'))
  } catch {
    return fallback
  }
}

export async function loadRuntimeFormulas(root) {
  if (runtimeModules) return runtimeModules

  const jsonDir = path.join(root, 'data', 'json')
  const originalFetch = globalThis.fetch
  globalThis.fetch = async url => {
    const clean = String(url).split('?')[0]
    const file = path.basename(clean)
    if (file === 'manifest.json') {
      return { ok: true, json: async () => ({ version: 'solver' }) }
    }
    const filePath = path.join(jsonDir, file)
    // premade-characters.json is being regenerated by the caller — an empty
    // array is fine, the solver never reads it back.
    const fallback = file === 'premade-characters.json' ? [] : null
    const data = loadJsonSafe(filePath, fallback)
    if (data === null) return { ok: false, json: async () => { throw new Error(`Missing ${file}`) } }
    return { ok: true, json: async () => data }
  }

  const { loadGameData } = await importJs('data.js')
  const { initCache } = await importJs('cache.js')
  const { computeStats } = await importJs('character.js')
  const { computeThreatLevel } = await importJs('threat-level.js')
  const { computeSkillLevel } = await importJs('skill-level.js')
  const { computeCombatPower } = await importJs('combat-power.js')

  await loadGameData()
  initCache()

  globalThis.fetch = originalFetch

  runtimeModules = { computeStats, computeThreatLevel, computeSkillLevel, computeCombatPower }
  return runtimeModules
}

/**
 * computeStats() mutates whatever object it's given, stashing the result on
 * `_cache.stats` for reuse. That's a great perf win at runtime, but deadly
 * here: object-spreading a previously-computed character silently inherits
 * its stale cache and computeStats short-circuits, ignoring new stats. Always
 * build a clean, cache-free character for every trial.
 */
function freshCharacter(base, stats) {
  return { ...base, stats, _cache: undefined }
}

function buildSheetStats(shape, multiplier) {
  const stats = { ...DEFAULT_STATS }
  for (const [stat, weight] of Object.entries(shape)) {
    if (!weight || weight <= 0) continue
    const rule = STAT_RULES[stat]
    if (!rule) continue
    const raw = DEFAULT_STATS[stat] + multiplier * weight
    stats[stat] = Math.min(rule.max, Math.max(rule.min, raw))
  }
  for (const stat of Object.keys(stats)) {
    stats[stat] = Math.round(stats[stat])
  }
  return stats
}

/**
 * Binary-search a single "investment" scalar across a stat shape (weights per
 * stat) until the real computeThreatLevel() lands on the target — accounting
 * for whatever gear/passive bonuses the skills+equipment already contribute.
 * Since every shape weight is >= 0, stat totals (and therefore threat) are
 * monotonic non-decreasing in the multiplier across the WHOLE real line, so a
 * single bisection also naturally handles low targets where starting gear
 * alone already overshoots — it just searches negative multipliers, trimming
 * stats down toward STAT_RULES min instead of only ever adding.
 */
export function solveStatsForThreatLevel({ computeThreatLevel, characterBase, shape, targetThreat }) {
  const base = { ...characterBase, _cache: undefined }

  const threatAt = multiplier => {
    const stats = buildSheetStats(shape, multiplier)
    const info = computeThreatLevel(freshCharacter(base, stats))
    return { multiplier, stats, info }
  }

  let lo = -4
  let hi = 4
  let loTrial = threatAt(lo)
  let hiTrial = threatAt(hi)
  let guard = 0
  while (hiTrial.info.threatLevel < targetThreat && guard < 60) {
    hi *= 2
    hiTrial = threatAt(hi)
    guard += 1
  }
  guard = 0
  while (loTrial.info.threatLevel > targetThreat && guard < 60) {
    lo *= 2
    loTrial = threatAt(lo)
    guard += 1
  }

  let best = loTrial.info.threatLevel === targetThreat ? loTrial : hiTrial
  if (Math.abs(loTrial.info.threatLevel - targetThreat) < Math.abs(best.info.threatLevel - targetThreat)) best = loTrial
  for (let i = 0; i < 70; i += 1) {
    const mid = (lo + hi) / 2
    const midTrial = threatAt(mid)
    if (Math.abs(midTrial.info.threatLevel - targetThreat) < Math.abs(best.info.threatLevel - targetThreat)) {
      best = midTrial
    }
    if (midTrial.info.threatLevel < targetThreat) {
      lo = mid
      loTrial = midTrial
    } else {
      hi = mid
      hiTrial = midTrial
    }
  }
  if (Math.abs(hiTrial.info.threatLevel - targetThreat) < Math.abs(best.info.threatLevel - targetThreat)) best = hiTrial
  if (Math.abs(loTrial.info.threatLevel - targetThreat) < Math.abs(best.info.threatLevel - targetThreat)) best = loTrial

  // Small integer nudge pass on the heaviest-weighted stat to close any
  // last-mile rounding gap left by the binary search.
  const [primaryStat] = Object.entries(shape).sort((a, b) => b[1] - a[1])[0] || []
  if (primaryStat && STAT_RULES[primaryStat]) {
    let guardNudge = 0
    while (best.info.threatLevel !== targetThreat && guardNudge < 300) {
      const direction = best.info.threatLevel < targetThreat ? 1 : -1
      const rule = STAT_RULES[primaryStat]
      const nextValue = Math.min(rule.max, Math.max(rule.min, best.stats[primaryStat] + direction))
      if (nextValue === best.stats[primaryStat]) break
      const trialStats = { ...best.stats, [primaryStat]: nextValue }
      const trialInfo = computeThreatLevel(freshCharacter(base, trialStats))
      const currentGap = Math.abs(best.info.threatLevel - targetThreat)
      const trialGap = Math.abs(trialInfo.threatLevel - targetThreat)
      if (trialGap > currentGap) break
      best = { stats: trialStats, info: trialInfo }
      guardNudge += 1
      if (trialGap === 0) break
    }
  }

  return { stats: best.stats, achievedThreatLevel: best.info.threatLevel, info: best.info }
}
